[package]
name = "micro-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
egui = "0.26.2"
glam = "0.25.0"
kira = "0.8.7"
micro = { git = "https://github.com/tesselode/micro", rev = "f2c04df" }
palette = "0.7.4"

[features]
sdl2_bundled = ["micro/sdl2_bundled"]

[profile.dev.package."*"]
opt-level = 3
